const conferences = [
  {
    id: 1,
    short: "ACM<br>ATC",
    logoClass: "",
    name: "ACM Symposium on Applied Computing (ATC 2026)",
    date: "Oct 15 – 17, 2026",
    location: "Quy Nhon, Vietnam",
    deadline: "16 Sep 2026",
    rank: "A",
    region: "Việt Nam",
    description: "ACM ATC focuses on applied computing, covering a broad range of topics in computer systems and applications.",
    tags: ["computer systems", "distributed computing", "cloud computing"],
    website: "#"
  },
  {
    id: 2,
    short: "SOICT<br>2026",
    logoClass: "logo-red",
    name: "The International Symposium on Information and Communication Technologies (SOICT 2026)",
    date: "Dec 10 – 12, 2026",
    location: "Ho Chi Minh City, Vietnam",
    deadline: "16 Sep 2026",
    rank: "B",
    region: "Việt Nam",
    description: "SOICT is an international forum for researchers and practitioners to present advances in information and communication technologies.",
    tags: ["information systems", "computer science", "communication"],
    website: "#"
  },
  {
    id: 3,
    short: "MAPR<br>2026",
    logoClass: "",
    name: "International Conference on Machine Learning and Pattern Recognition (MAPR 2026)",
    date: "Jul 19 – 21, 2026",
    location: "Hue City, Vietnam",
    deadline: "15 May 2026",
    rank: "B",
    region: "Việt Nam",
    description: "MAPR focuses on machine learning, pattern recognition and their applications in real-world problems.",
    tags: ["machine learning", "pattern recognition", "artificial intelligence"],
    website: "#"
  },
  {
    id: 4,
    short: "NeurIPS<br>2026",
    logoClass: "logo-purple",
    name: "Conference on Neural Information Processing Systems",
    date: "Dec 6 – 12, 2026",
    location: "New Orleans, USA",
    deadline: "13 May 2026",
    rank: "A*",
    region: "Quốc tế",
    description: "NeurIPS is a premier conference on machine learning and computational neuroscience.",
    tags: ["machine learning", "deep learning", "neural networks"],
    website: "#"
  },
  {
    id: 5,
    short: "ICLR<br>2026",
    logoClass: "logo-green",
    name: "International Conference on Learning Representations",
    date: "Apr 26 – 30, 2026",
    location: "Singapore",
    deadline: "22 Oct 2025",
    rank: "A*",
    region: "Quốc tế",
    description: "ICLR is a top conference on representation learning, deep learning and related areas.",
    tags: ["representation learning", "deep learning", "AI"],
    website: "#"
  },
  {
    id: 6,
    short: "ACL",
    logoClass: "logo-red",
    name: "Annual Meeting of the Association for Computational Linguistics",
    date: "Jul 12 – 17, 2026",
    location: "Vienna, Austria",
    deadline: "15 Jan 2026",
    rank: "A",
    region: "Quốc tế",
    description: "ACL is the main international conference for research in computational linguistics and natural language processing.",
    tags: ["NLP", "computational linguistics", "language models"],
    website: "#"
  }
];
